-- Phase 7C: Daily Event Code
--
-- Purpose:
-- Event shift access for operational users requires a daily code generated by
-- a manager or event_floor_manager. Codes are stored hashed only.
--
-- Manual setup:
-- 1. Run this migration after the Phase 7A shared-device migration.
-- 2. Make sure Julie/event responsible users have role = 'event_floor_manager'
--    or managers have role = 'manager' in public.user_profiles.
-- 3. Do not store permanent event codes, passwords, PINs or private credentials
--    in frontend source code or SQL comments.

create extension if not exists pgcrypto with schema extensions;

create table if not exists public.event_access_codes (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid default public.current_user_organization_id(),
  code_date date not null,
  code_hash text not null,
  expires_at timestamptz not null,
  generated_by_auth_user_id uuid default auth.uid(),
  generated_by_name text,
  active boolean not null default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists event_access_codes_org_date_idx
on public.event_access_codes (organization_id, code_date desc);

create index if not exists event_access_codes_active_idx
on public.event_access_codes (active, expires_at);

drop trigger if exists event_access_codes_set_updated_at on public.event_access_codes;
create trigger event_access_codes_set_updated_at
before update on public.event_access_codes
for each row
execute function public.set_updated_at();

alter table public.event_access_codes enable row level security;

grant select, insert, update on public.event_access_codes to authenticated;

create or replace function public.current_user_is_shared_device()
returns boolean
language sql
security definer
set search_path = public
as $$
  select coalesce((
    select is_shared_device
    from public.user_profiles
    where id = auth.uid()
    limit 1
  ), false);
$$;

create or replace function public.current_user_can_manage_event_codes()
returns boolean
language sql
security definer
set search_path = public
as $$
  select public.current_user_profile_role() in ('manager', 'event_floor_manager')
    and not public.current_user_is_shared_device();
$$;

drop policy if exists "event_access_codes_select_managers" on public.event_access_codes;
create policy "event_access_codes_select_managers"
on public.event_access_codes for select
to authenticated
using (
  public.current_user_can_manage_event_codes()
  and (
    organization_id is null
    or public.current_user_organization_id() is null
    or organization_id = public.current_user_organization_id()
  )
);

drop policy if exists "event_access_codes_insert_managers" on public.event_access_codes;
create policy "event_access_codes_insert_managers"
on public.event_access_codes for insert
to authenticated
with check (
  public.current_user_can_manage_event_codes()
  and generated_by_auth_user_id = auth.uid()
  and (
    organization_id is null
    or public.current_user_organization_id() is null
    or organization_id = public.current_user_organization_id()
  )
);

drop policy if exists "event_access_codes_update_managers" on public.event_access_codes;
create policy "event_access_codes_update_managers"
on public.event_access_codes for update
to authenticated
using (
  public.current_user_can_manage_event_codes()
  and (
    organization_id is null
    or public.current_user_organization_id() is null
    or organization_id = public.current_user_organization_id()
  )
)
with check (
  public.current_user_can_manage_event_codes()
  and (
    organization_id is null
    or public.current_user_organization_id() is null
    or organization_id = public.current_user_organization_id()
  )
);

create or replace function public.generate_daily_event_code()
returns table (
  code text,
  code_date date,
  expires_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_org uuid;
  v_date date;
  v_expires timestamptz;
  v_code text;
  v_name text;
begin
  if not public.current_user_can_manage_event_codes() then
    raise exception 'Only manager or event floor manager can generate event codes.';
  end if;

  v_org := public.current_user_organization_id();
  v_date := (now() at time zone 'Europe/Oslo')::date;
  v_expires := ((v_date + 1)::timestamp at time zone 'Europe/Oslo');
  v_code := lpad((((('x' || substr(encode(extensions.gen_random_bytes(4), 'hex'), 1, 8))::bit(32)::bigint) % 1000000))::text, 6, '0');

  select display_name
  into v_name
  from public.user_profiles
  where id = auth.uid()
  limit 1;

  update public.event_access_codes as c
  set active = false
  where c.active = true
    and c.code_date = v_date
    and c.organization_id is not distinct from v_org;

  insert into public.event_access_codes (
    organization_id,
    code_date,
    code_hash,
    expires_at,
    generated_by_auth_user_id,
    generated_by_name,
    active
  )
  values (
    v_org,
    v_date,
    extensions.crypt(v_code, extensions.gen_salt('bf')),
    v_expires,
    auth.uid(),
    coalesce(v_name, 'Unknown'),
    true
  );

  return query select v_code, v_date, v_expires;
end;
$$;

create or replace function public.validate_daily_event_code(input_code text)
returns table (
  valid boolean,
  status text,
  message text,
  code_date date,
  expires_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_org uuid;
  v_date date;
  v_record public.event_access_codes%rowtype;
begin
  if not public.current_user_is_active() then
    return query select false, 'auth_required', 'Email login required to validate event code.', null::date, null::timestamptz;
    return;
  end if;

  v_org := public.current_user_organization_id();
  v_date := (now() at time zone 'Europe/Oslo')::date;

  if input_code is null or length(trim(input_code)) < 4 then
    return query select false, 'invalid', 'Enter today''s event code.', v_date, null::timestamptz;
    return;
  end if;

  select *
  into v_record
  from public.event_access_codes
  where active = true
    and code_date = v_date
    and expires_at > now()
    and organization_id is not distinct from v_org
  order by created_at desc
  limit 1;

  if not found then
    return query select false, 'expired_or_missing', 'Today''s event code is missing or expired.', v_date, null::timestamptz;
    return;
  end if;

  if v_record.code_hash = extensions.crypt(trim(input_code), v_record.code_hash) then
    return query select true, 'valid', 'Event shift unlocked.', v_record.code_date, v_record.expires_at;
    return;
  end if;

  return query select false, 'invalid', 'Event code is not valid for today.', v_record.code_date, v_record.expires_at;
end;
$$;

grant execute on function public.generate_daily_event_code() to authenticated;
grant execute on function public.validate_daily_event_code(text) to authenticated;
