import { useState } from "react";
import { createIdempotencyKey, moveEntry } from "../data/routineManagerModel.js";
import { useRoutineOperatorAdmin } from "../hooks/useRoutineOperatorAdmin.js";
import { EmptyState, Field, Modal, MoveButtons, StatusPill } from "./RoutineManagerPrimitives.jsx";

const defaultDevice = { userProfileId: "", deviceKey: "", label: "", settings: { absoluteSessionMinutes: 960, idleTimeoutMinutes: 30, criticalReauthMinutes: 5, maxFailedAttempts: 5, failureWindowMinutes: 15, lockoutMinutes: 15, allowOfflineNoncriticalDrafts: true } };
const defaultOperator = { operatorKey: "", operatorType: "temporary", linkedUserProfileId: "", displayName: "", effectiveRole: "staff", validFrom: "", validUntil: "" };
const capabilityKeys = [
  ["allowTaskActions", "Task actions"],
  ["allowCriticalActions", "Critical actions"],
  ["allowRunCoordination", "Coordination"],
  ["allowEventTransferActions", "Event transfer"],
  ["allowOfflineNoncritical", "Offline noncritical"],
];
const accessValue = (row, camel, snake) => row[camel] ?? row[snake] ?? false;
const normalizeAccess = (row) => ({ operatorId: row.operatorId || row.operator_id, active: row.active !== false, validFrom: row.validFrom || row.valid_from || null, validUntil: row.validUntil || row.valid_until || null, sortOrder: row.sortOrder ?? row.sort_order ?? 0, allowTaskActions: accessValue(row, "allowTaskActions", "allow_task_actions"), allowCriticalActions: accessValue(row, "allowCriticalActions", "allow_critical_actions"), allowRunCoordination: accessValue(row, "allowRunCoordination", "allow_run_coordination"), allowEventTransferActions: accessValue(row, "allowEventTransferActions", "allow_event_transfer_actions"), allowOfflineNoncritical: accessValue(row, "allowOfflineNoncritical", "allow_offline_noncritical") });

export default function RoutineOperatorAdmin({ loader, api, profileChoices = [] }) {
  const admin = useRoutineOperatorAdmin({ loader, api });
  const [device, setDevice] = useState(null);
  const [operator, setOperator] = useState(null);
  const [accessDevice, setAccessDevice] = useState(null);
  const [accessEntries, setAccessEntries] = useState([]);
  const [pinDialog, setPinDialog] = useState(null);
  const [pin, setPin] = useState("");
  const [pinConfirm, setPinConfirm] = useState("");
  const [message, setMessage] = useState("");
  const clearPinDialog = () => { setPin(""); setPinConfirm(""); setPinDialog(null); };
  const sendPin = async () => {
    if (pin !== pinConfirm) { setMessage("PIN confirmation does not match."); setPin(""); setPinConfirm(""); return; }
    try {
      const payload = pinDialog.kind === "create" ? { ...pinDialog.operator, initialPin: pin, idempotencyKey: createIdempotencyKey() } : { operatorId: pinDialog.operator.id, newPin: pin, reason: pinDialog.reason || "Manager PIN rotation", expectedOperatorRevision: pinDialog.operator.revision, idempotencyKey: createIdempotencyKey() };
      const result = await admin.mutate(pinDialog.kind === "create" ? "createOperator" : "rotatePin", payload);
      setMessage(result.ok ? "Credential request completed. PIN is no longer available." : "Credential request failed. PIN was cleared.");
      if (result.ok) { setPinDialog(null); setOperator(null); }
    } finally { setPin(""); setPinConfirm(""); }
  };
  const selectDeviceAccess = (entry) => {
    setAccessDevice(entry);
    setAccessEntries((admin.data?.access || []).filter((row) => (row.sharedDeviceId || row.shared_device_id) === entry.id).map(normalizeAccess));
  };
  const saveAccess = async () => {
    const result = await admin.mutate("replaceAccess", { sharedDeviceId: accessDevice.id, accessEntries, expectedDeviceRevision: accessDevice.revision, idempotencyKey: createIdempotencyKey() });
    setMessage(result.ok ? "Complete device/operator access state saved." : "Access save failed; local desired state remains visible.");
  };
  const invalidReason = (entry) => {
    const selected = admin.data?.operators?.find((candidate) => candidate.id === entry.operatorId);
    if (entry.allowCriticalActions && !entry.allowTaskActions) return "Critical actions require task actions.";
    if ((entry.allowRunCoordination || entry.allowEventTransferActions) && !selected?.linkedProfileId) return "Coordination and Event transfer require a linked profile.";
    if (entry.allowOfflineNoncritical && !accessDevice?.allowOfflineNoncriticalDrafts) return "Device policy disables offline drafts.";
    return "";
  };
  const accessInvalid = accessEntries.some(invalidReason);

  return <section className="rm-stack">
    <header className="rm-section-heading"><div><p className="eyebrow">Shared-device security</p><h2>Operator and device administration</h2></div><div className="rm-actions"><button type="button" className="ghost-button" onClick={() => setDevice(defaultDevice)}>Register device</button><button type="button" className="primary-button" onClick={() => setOperator(defaultOperator)}>Create operator</button></div></header>
    <div className="rm-split">
      <section className="rm-card"><h3>Devices</h3>{!admin.data?.devices?.length ? <EmptyState title="No shared devices">Register only a pre-approved shared-device profile.</EmptyState> : <div className="rm-list">{admin.data.devices.map((entry) => <button type="button" key={entry.id} onClick={() => setDevice({ ...entry, settings: { absoluteSessionMinutes: entry.absoluteSessionMinutes, idleTimeoutMinutes: entry.idleTimeoutMinutes, criticalReauthMinutes: entry.criticalReauthMinutes, maxFailedAttempts: entry.maxFailedAttempts, failureWindowMinutes: entry.failureWindowMinutes, lockoutMinutes: entry.lockoutMinutes, allowOfflineNoncriticalDrafts: entry.allowOfflineNoncriticalDrafts } })}><span><strong>{entry.label}</strong><small>{entry.deviceKey} · rev {entry.revision}</small></span><StatusPill state={entry.active ? "ready" : "blocked"}>{entry.active ? "Active" : "Disabled"}</StatusPill></button>)}</div>}</section>
      <section className="rm-card"><h3>Operators</h3>{!admin.data?.operators?.length ? <EmptyState title="No operators">Create a temporary or linked operator with an ephemeral initial PIN.</EmptyState> : <div className="rm-list">{admin.data.operators.map((entry) => <button type="button" key={entry.id} onClick={() => setOperator(entry)}><span><strong>{entry.displayName}</strong><small>{entry.operatorType} · {entry.role} · {entry.validUntil ? `valid until ${entry.validUntil}` : "no end date"}</small></span><StatusPill state={entry.active ? "ready" : "blocked"}>{entry.active ? "Active" : "Disabled"}</StatusPill></button>)}</div>}</section>
    </div>
    {device ? <form className="rm-card rm-form" onSubmit={async (event) => { event.preventDefault(); const result = await admin.mutate(device.id ? "updateDevice" : "registerDevice", device.id ? { sharedDeviceId: device.id, label: device.label, settings: device.settings, expectedRevision: device.revision, idempotencyKey: createIdempotencyKey() } : { ...device, idempotencyKey: createIdempotencyKey() }); if (result.ok) setDevice(null); }}>
      <h3>{device.id ? "Device policy" : "Register shared-device profile"}</h3>
      {!device.id ? <div className="rm-field-grid"><Field id="device-profile" label="Shared-device profile" help="Personal profiles are rejected by the server."><select id="device-profile" value={device.userProfileId} onChange={(event) => setDevice({ ...device, userProfileId: event.target.value })}><option value="">Choose…</option>{profileChoices.filter((profile) => profile.isSharedDevice).map((profile) => <option value={profile.id} key={profile.id}>{profile.displayName}</option>)}</select></Field><Field id="device-key" label="Device key" help="Stable device identity."><input id="device-key" value={device.deviceKey} onChange={(event) => setDevice({ ...device, deviceKey: event.target.value })} /></Field></div> : null}
      <Field id="device-label" label="Label" help="Visible device label."><input id="device-label" value={device.label} onChange={(event) => setDevice({ ...device, label: event.target.value })} /></Field>
      <div className="rm-policy-grid">{[["absoluteSessionMinutes", "Absolute session", 60, 1440], ["idleTimeoutMinutes", "Idle timeout", 5, 240], ["criticalReauthMinutes", "Critical reauth", 1, 30], ["maxFailedAttempts", "Max failures", 3, 20], ["failureWindowMinutes", "Failure window", 1, 120], ["lockoutMinutes", "Lockout", 1, 1440]].map(([key, label, min, max]) => <Field id={`device-${key}`} label={label} help={`${min}–${max} minutes/count`} key={key}><input id={`device-${key}`} type="number" min={min} max={max} value={device.settings[key]} onChange={(event) => setDevice({ ...device, settings: { ...device.settings, [key]: Number(event.target.value) } })} /></Field>)}</div>
      <label className="rm-check"><input type="checkbox" checked={device.settings.allowOfflineNoncriticalDrafts} onChange={(event) => setDevice({ ...device, settings: { ...device.settings, allowOfflineNoncriticalDrafts: event.target.checked } })} /> Allow offline noncritical drafts</label>
      <div className="rm-actions"><button className="primary-button">Save device</button>{device.id ? <><button type="button" className="ghost-button" onClick={() => selectDeviceAccess(device)}>Edit operator access</button><button type="button" className="ghost-button" onClick={async () => { const result = await admin.mutate("setDeviceActive", { sharedDeviceId: device.id, active: !device.active, reason: "Manager changed shared-device availability.", expectedRevision: device.revision, idempotencyKey: createIdempotencyKey() }); if (result.ok) setDevice(null); }}>{device.active ? "Disable device" : "Activate device"}</button></> : null}</div>
      {device.id && device.active ? <p className="rm-note">Disabling this device revokes its active sessions.</p> : null}
    </form> : null}
    {operator ? <form className="rm-card rm-form" onSubmit={(event) => { event.preventDefault(); if (operator.id) admin.mutate("updateOperator", { operatorId: operator.id, displayName: operator.displayName, effectiveRole: operator.role, validFrom: operator.validFrom || null, validUntil: operator.validUntil || null, expectedRevision: operator.revision, idempotencyKey: createIdempotencyKey() }); else setPinDialog({ kind: "create", operator }); }}>
      <h3>{operator.id ? "Operator" : "New operator"}</h3>
      {!operator.id ? <><div className="rm-field-grid"><Field id="operator-key" label="Operator key" help="Stable operator identity."><input id="operator-key" value={operator.operatorKey} onChange={(event) => setOperator({ ...operator, operatorKey: event.target.value })} /></Field><Field id="operator-type" label="Type" help="Temporary operators are limited to staff/time2staff."><select id="operator-type" value={operator.operatorType} onChange={(event) => setOperator({ ...operator, operatorType: event.target.value, linkedUserProfileId: "" })}><option value="temporary">temporary</option><option value="linked_profile">linked profile</option></select></Field></div>{operator.operatorType === "linked_profile" ? <Field id="operator-linked-profile" label="Linked personal profile" help="Manager, counter, and shared-device profiles are never offered."><select id="operator-linked-profile" value={operator.linkedUserProfileId} onChange={(event) => setOperator({ ...operator, linkedUserProfileId: event.target.value })}><option value="">Choose…</option>{profileChoices.filter((profile) => !profile.isSharedDevice && !["manager", "counter"].includes(profile.role)).map((profile) => <option key={profile.id} value={profile.id}>{profile.displayName} · {profile.role}</option>)}</select></Field> : null}</> : null}
      <Field id="operator-name" label="Display name" help="Never contains PIN."><input id="operator-name" value={operator.displayName || ""} onChange={(event) => setOperator({ ...operator, displayName: event.target.value })} /></Field>
      <div className="rm-three-grid"><Field id="operator-role" label="Effective role" help="Manager and counter cannot be operators."><select id="operator-role" value={operator.role || operator.effectiveRole} onChange={(event) => setOperator({ ...operator, [operator.id ? "role" : "effectiveRole"]: event.target.value })}>{["staff", "time2staff", "shift_lead", "event_floor_manager"].map((value) => <option key={value}>{value}</option>)}</select></Field><Field id="operator-valid-from" label="Valid from" help="Optional server-validated validity."><input id="operator-valid-from" type="datetime-local" value={operator.validFrom?.slice?.(0, 16) || ""} onChange={(event) => setOperator({ ...operator, validFrom: event.target.value || null })} /></Field><Field id="operator-valid-until" label="Valid until" help="Optional server-validated validity."><input id="operator-valid-until" type="datetime-local" value={operator.validUntil?.slice?.(0, 16) || ""} onChange={(event) => setOperator({ ...operator, validUntil: event.target.value || null })} /></Field></div>
      <div className="rm-actions"><button className="primary-button">{operator.id ? "Save operator" : "Continue to initial PIN"}</button>{operator.id ? <><button type="button" className="ghost-button" onClick={() => setPinDialog({ kind: "rotate", operator })}>Rotate PIN</button><button type="button" className="ghost-button" onClick={() => admin.mutate("setOperatorActive", { operatorId: operator.id, active: !operator.active, reason: "Manager changed operator availability.", expectedRevision: operator.revision, idempotencyKey: createIdempotencyKey() })}>{operator.active ? "Deactivate" : "Activate"}</button></> : null}</div>
    </form> : null}
    {accessDevice ? <section className="rm-card rm-form"><header><div><h3>Access · {accessDevice.label}</h3><p>Complete desired state; order is keyboard controlled.</p></div><button type="button" className="ghost-button" onClick={() => setAccessDevice(null)}>Close access editor</button></header>
      {accessEntries.map((entry, index) => { const selected = admin.data?.operators?.find((candidate) => candidate.id === entry.operatorId); const reason = invalidReason(entry); return <div className="rm-subpanel" key={entry.operatorId}><header><strong>{selected?.displayName || entry.operatorId}</strong><MoveButtons index={index} total={accessEntries.length} label={selected?.displayName || "operator"} onMove={(direction) => setAccessEntries(moveEntry(accessEntries, index, direction))} /></header><div className="rm-actions">{capabilityKeys.map(([key, label]) => <label className="rm-check" key={key}><input type="checkbox" checked={entry[key]} onChange={(event) => setAccessEntries(accessEntries.map((value, entryIndex) => entryIndex === index ? { ...value, [key]: event.target.checked } : value))} /> {label}</label>)}</div>{reason ? <p className="rm-inline-blocker" role="alert">{reason}</p> : <p className="rm-note">Effective capability is the intersection of access, device policy, operator role, and server session state.</p>}<button type="button" className="ghost-button" onClick={() => setAccessEntries(accessEntries.filter((_, entryIndex) => entryIndex !== index))}>Remove from device</button></div>; })}
      <Field id="access-add-operator" label="Add operator" help="Duplicate operators are not offered."><select id="access-add-operator" value="" onChange={(event) => { if (event.target.value) setAccessEntries([...accessEntries, { operatorId: event.target.value, active: true, validFrom: null, validUntil: null, sortOrder: accessEntries.length, allowTaskActions: true, allowCriticalActions: false, allowRunCoordination: false, allowEventTransferActions: false, allowOfflineNoncritical: accessDevice.allowOfflineNoncriticalDrafts }]); }}><option value="">Choose…</option>{(admin.data?.operators || []).filter((candidate) => !accessEntries.some((entry) => entry.operatorId === candidate.id)).map((candidate) => <option value={candidate.id} key={candidate.id}>{candidate.displayName} · {candidate.role}</option>)}</select></Field>
      <button type="button" className="primary-button" disabled={accessInvalid} onClick={saveAccess}>Save complete operator access</button>
    </section> : null}
    <section className="rm-card"><h3>Sanitized security history</h3><p>{admin.data?.sessions?.length || 0} recent sessions · {admin.data?.lockouts?.length || 0} lockouts. Credential hashes, session secrets, tokens and PIN values are never returned.</p><div className="rm-list">{admin.data?.sessions?.map((session) => <div className="rm-list-row" key={session.id}><span><strong>{session.status}</strong><small>{session.authenticatedAt || session.authenticated_at} · expires {session.expiresAt || session.expires_at}</small></span>{session.status === "active" ? <button type="button" className="ghost-button" onClick={() => admin.mutate("revokeSession", { operatorSessionId: session.id, reason: "Manager revoked active shared-device session.", expectedRevision: session.revision, idempotencyKey: createIdempotencyKey() })}>Revoke</button> : null}</div>)}</div></section>
    {pinDialog ? <Modal title={pinDialog.kind === "create" ? "Set initial PIN" : "Rotate operator PIN"} onClose={clearPinDialog} actions={<><button type="button" className="ghost-button" onClick={clearPinDialog}>Cancel</button><button type="button" className="primary-button" disabled={pin.length < 6 || pin !== pinConfirm} onClick={sendPin}>Send once</button></>}><Field id="operator-pin" label="PIN" help="6–12 digits. Never stored or logged."><input id="operator-pin" type="password" inputMode="numeric" autoComplete="off" autoCorrect="off" spellCheck={false} value={pin} onChange={(event) => setPin(event.target.value.replace(/\D/g, "").slice(0, 12))} /></Field><Field id="operator-pin-confirm" label="Confirm PIN" help="Both fields clear after every request."><input id="operator-pin-confirm" type="password" inputMode="numeric" autoComplete="off" autoCorrect="off" spellCheck={false} value={pinConfirm} onChange={(event) => setPinConfirm(event.target.value.replace(/\D/g, "").slice(0, 12))} /></Field></Modal> : null}
    <p role="status">{message}</p>
  </section>;
}
