create or replace function phase10l_test.assert(input_number integer,input_label text,input_condition boolean)
returns text language plpgsql as $$
begin
  if not coalesce(input_condition,false) then raise exception 'FAIL % %',input_number,input_label; end if;
  return 'PASS '||lpad(input_number::text,3,'0')||' '||input_label;
end;
$$;

select phase10l_test.assert(1,'preview is valid before installation',(select (value->>'valid')::boolean from phase10l_test.state where key='preview'));
select phase10l_test.assert(2,'preview reports exact O/C/DS counts',(select value->'counts'->>'openingTasks'='37' and value->'counts'->>'closingTasks'='46' and value->'counts'->>'doubleShiftSteps'='4' from phase10l_test.state where key='preview'));
select phase10l_test.assert(3,'install returns editable resources only',(select value->>'installStatus'='installed' and not (value->>'published')::boolean and not (value->>'runsCreated')::boolean from phase10l_test.state where key='install'));
select phase10l_test.assert(4,'same request replays immutably',(select (value->>'idempotentReplay')::boolean and value->>'installationId'=(select value->>'installationId' from phase10l_test.state where key='install') from phase10l_test.state where key='replay'));
select phase10l_test.assert(5,'new key reports already installed',(select value->>'installStatus'='already_installed' from phase10l_test.state where key='already_installed'));
select phase10l_test.assert(6,'one installation exists',(select count(*)=1 from public.routine_content_pack_installations where organization_id='a1000000-0000-4000-8000-000000000001'));
select phase10l_test.assert(7,'two immutable install operations exist',(select count(*)=2 from public.routine_content_pack_operations where organization_id='a1000000-0000-4000-8000-000000000001'));
select phase10l_test.assert(8,'only Opening and Closing templates were created',(select count(*)=2 and bool_and(routine_key in('opening','closing')) from public.routine_templates where organization_id='a1000000-0000-4000-8000-000000000001'));
select phase10l_test.assert(9,'no Double Shift template exists',not exists(select 1 from public.routine_templates where organization_id='a1000000-0000-4000-8000-000000000001' and routine_key in('double_shift','double-shift')));
select phase10l_test.assert(10,'Opening has 37 draft tasks',(select count(*)=37 from public.routine_template_tasks task join public.routine_template_versions version on version.id=task.version_id join public.routine_templates template on template.id=version.template_id where template.organization_id='a1000000-0000-4000-8000-000000000001' and template.routine_key='opening' and version.state='draft'));
select phase10l_test.assert(11,'Closing has 46 draft tasks',(select count(*)=46 from public.routine_template_tasks task join public.routine_template_versions version on version.id=task.version_id join public.routine_templates template on template.id=version.template_id where template.organization_id='a1000000-0000-4000-8000-000000000001' and template.routine_key='closing' and version.state='draft'));
select phase10l_test.assert(12,'Opening has exactly three sections',(select count(*)=3 from public.routine_template_sections section join public.routine_template_versions version on version.id=section.version_id join public.routine_templates template on template.id=version.template_id where template.organization_id='a1000000-0000-4000-8000-000000000001' and template.routine_key='opening' and version.state='draft'));
select phase10l_test.assert(13,'Closing has exactly two sections',(select count(*)=2 from public.routine_template_sections section join public.routine_template_versions version on version.id=section.version_id join public.routine_templates template on template.id=version.template_id where template.organization_id='a1000000-0000-4000-8000-000000000001' and template.routine_key='closing' and version.state='draft'));
select phase10l_test.assert(14,'room 005 does not exist',not exists(select 1 from public.routine_locations where organization_id='a1000000-0000-4000-8000-000000000001' and (location_key~'005' or name='005')));
select phase10l_test.assert(15,'milk-fridge standard is exact',(select revision.value_json='{"regularMilk":2,"oatly":2}'::jsonb from public.routine_standards standard join public.routine_standard_revisions revision on revision.id=standard.current_revision_id where standard.organization_id='a1000000-0000-4000-8000-000000000001' and standard.standard_key='workbar-milk-fridge-target'));
select phase10l_test.assert(16,'all nine unresolved standards have no current revision',(select count(*)=9 and bool_and(current_revision_id is null) from public.routine_standards where organization_id='a1000000-0000-4000-8000-000000000001' and standard_key in('coffee-canister-total-inventory-target','coffee-cups-full-target','coffee-cups-service-ready-target','wine-glasses-full-target','wine-glasses-service-ready-target','self-service-tea-slot-names','serviceware-office-recovery-route-confirmation','door-and-lock-rules','fridge-closing-rules')));
select phase10l_test.assert(17,'O13 source includes eggs',exists(select 1 from public.routine_template_tasks task where task.organization_id='a1000000-0000-4000-8000-000000000001' and task.task_key like 'o13-%' and (task.title ilike '%egg%' or task.instructions ilike '%egg%' or task.metadata::text ilike '%egg%')));
select phase10l_test.assert(18,'O27 completes through O29',exists(select 1 from public.routine_template_task_dependencies dependency join public.routine_template_tasks predecessor on predecessor.id=dependency.predecessor_task_id join public.routine_template_tasks successor on successor.id=dependency.successor_task_id where predecessor.task_key like 'o27-%' and successor.task_key like 'o29-%' and dependency.dependency_type='complete_predecessor_on_successor'));
select phase10l_test.assert(19,'O33 completes through O35',exists(select 1 from public.routine_template_task_dependencies dependency join public.routine_template_tasks predecessor on predecessor.id=dependency.predecessor_task_id join public.routine_template_tasks successor on successor.id=dependency.successor_task_id where predecessor.task_key like 'o33-%' and successor.task_key like 'o35-%' and dependency.dependency_type='complete_predecessor_on_successor'));
select phase10l_test.assert(20,'final checkpoints retain independent task identities',(select count(distinct task_key)=2 from public.routine_template_tasks where organization_id='a1000000-0000-4000-8000-000000000001' and (task_key like 'o29-%' or task_key like 'o35-%')));
select phase10l_test.assert(21,'delivery relations use same-scope evidence',not exists(select 1 from public.routine_template_task_relations where organization_id='a1000000-0000-4000-8000-000000000001' and relation_type='delivery_comparison' and (metadata->>'scopePolicy'<>'same_scope' or jsonb_array_length(metadata->'evidenceItemKeys')=0)));
select phase10l_test.assert(22,'Previous Closing evidence cannot auto-complete Opening',not exists(select 1 from public.routine_template_task_relations where organization_id='a1000000-0000-4000-8000-000000000001' and relation_type='delivery_comparison' and coalesce((metadata->>'autoComplete')::boolean,false)));
select phase10l_test.assert(23,'pre-restock is not linked as final completion',not exists(select 1 from public.routine_template_task_dependencies dependency join public.routine_template_tasks predecessor on predecessor.id=dependency.predecessor_task_id join public.routine_template_tasks successor on successor.id=dependency.successor_task_id where predecessor.task_key~'^c(08|09|10)-' and successor.task_key~'^c(28|29|30)-' and dependency.dependency_type='complete_predecessor_on_successor'));
select phase10l_test.assert(24,'all logical references are placeholders',(select count(*)=33 and bool_and(version.state='placeholder') from public.routine_reference_images reference join public.routine_reference_image_versions version on version.id=reference.current_version_id where reference.organization_id='a1000000-0000-4000-8000-000000000001'));
select phase10l_test.assert(25,'reference button copy is exact',not exists(select 1 from public.routine_template_task_reference_images where organization_id='a1000000-0000-4000-8000-000000000001' and button_label<>'Vis hvordan det skal se ut'));
select phase10l_test.assert(26,'serviceware route is explicitly incomplete',exists(select 1 from public.routine_location_sets location_set join public.routine_location_set_members member on member.location_set_id=location_set.id where location_set.organization_id='a1000000-0000-4000-8000-000000000001' and location_set.set_key='serviceware-recovery-route' and (member.metadata->>'managerIncomplete')::boolean));
select phase10l_test.assert(27,'inventory source uses authoritative location code',not exists(select 1 from public.routine_template_task_items where organization_id='a1000000-0000-4000-8000-000000000001' and source_kind='inventory_readonly' and source_config->>'locationCode'<>'WORKBAR_NON_ALCO_FRIDGE'));
select phase10l_test.assert(28,'install preserves mode and release stage',(select (select value from phase10l_test.state where key='before_state')->>'mode'=(select value from phase10l_test.state where key='after_state')->>'mode' and (select value from phase10l_test.state where key='before_state')->>'stage'=(select value from phase10l_test.state where key='after_state')->>'stage'));
select phase10l_test.assert(29,'install creates no operative state',(select (select value from phase10l_test.state where key='before_state')-array['mode','stage']=(select value from phase10l_test.state where key='after_state')-array['mode','stage']));
select phase10l_test.assert(30,'release readiness remains blocked',(select not (value->>'ready')::boolean and jsonb_array_length(value->'categories'->'operationalContent'->'blockers')>=9 from phase10l_test.state where key='readiness'));
select phase10l_test.assert(31,'readiness models DS as four system steps',(select value->'categories'->'operationalContent'->'evidenceCounts'->>'doubleShiftSteps'='4' and value->'categories'->'operationalContent'->'evidenceCounts'->>'doubleShiftTemplates'='0' from phase10l_test.state where key='readiness'));
select phase10l_test.assert(32,'audit reports no initial semantic divergence',(select not (value->'semanticDivergence'->>'opening')::boolean and not (value->'semanticDivergence'->>'closing')::boolean from phase10l_test.state where key='audit'));
select phase10l_test.assert(33,'staff is denied manager pack access',(select value='true'::jsonb from phase10l_test.state where key='staff_denied'));
select phase10l_test.assert(34,'shared-device manager is denied',(select value='true'::jsonb from phase10l_test.state where key='shared_denied'));
select phase10l_test.assert(35,'semantic conflict blocks preview',(select not (value->>'valid')::boolean and jsonb_array_length(value->'conflicts')>0 from phase10l_test.state where key='conflict_preview'));
select phase10l_test.assert(36,'application roles have no table DML',not has_table_privilege('authenticated','public.routine_content_pack_installations','INSERT,UPDATE,DELETE') and not has_table_privilege('authenticated','public.routine_content_pack_operations','INSERT,UPDATE,DELETE'));
select phase10l_test.assert(37,'anonymous has no pack function access',not has_function_privilege('anon','public.preview_mesh_routine_content_pack_v1()','EXECUTE') and not has_function_privilege('anon','public.install_mesh_routine_content_pack_v1(text,text,uuid)','EXECUTE'));
select phase10l_test.assert(38,'authenticated has only explicit entry points',has_function_privilege('authenticated','public.preview_mesh_routine_content_pack_v1()','EXECUTE') and has_function_privilege('authenticated','public.install_mesh_routine_content_pack_v1(text,text,uuid)','EXECUTE') and not has_function_privilege('authenticated','public.routine_mesh_content_pack_analysis(uuid)','EXECUTE'));
select phase10l_test.assert(39,'installation rows are immutable',(select count(*)=1 from pg_trigger where tgrelid='public.routine_content_pack_installations'::regclass and tgname='routine_content_pack_installations_immutable' and not tgisinternal));
select phase10l_test.assert(40,'operations are immutable',(select count(*)=1 from pg_trigger where tgrelid='public.routine_content_pack_operations'::regclass and tgname='routine_content_pack_operations_immutable' and not tgisinternal));
