create or replace function phase10j_test.ok(condition boolean,label text)
returns void language plpgsql as $$
begin
  if not coalesce(condition,false) then raise exception 'FAIL %',label; end if;
  raise notice 'PASS %',label;
end $$;

select phase10j_test.ok(to_regclass('public.routine_shared_devices') is not null,'001 shared devices table');
select phase10j_test.ok(to_regclass('public.routine_operators') is not null,'002 operators table');
select phase10j_test.ok(to_regclass('public.routine_shared_device_operator_access') is not null,'003 access table');
select phase10j_test.ok(to_regclass('public.routine_operator_credentials') is not null,'004 credentials table');
select phase10j_test.ok(to_regclass('public.routine_operator_auth_throttles') is not null,'005 throttles table');
select phase10j_test.ok(to_regclass('public.routine_operator_auth_attempts') is not null,'006 attempts table');
select phase10j_test.ok(to_regclass('public.routine_operator_sessions') is not null,'007 sessions table');
select phase10j_test.ok(to_regclass('public.routine_operator_operations') is not null,'008 operations table');
select phase10j_test.ok(to_regclass('public.routine_operator_events') is not null,'009 events table');
select phase10j_test.ok((select count(*)=1 from public.routine_shared_devices),'010 one enrolled test device');
select phase10j_test.ok((select count(*)=2 from public.routine_operators),'011 linked and temporary operators');
select phase10j_test.ok((select count(*)=2 from public.routine_shared_device_operator_access where active),'012 two active access rows');
select phase10j_test.ok((select count(*)=2 from public.routine_operator_credentials where status='active'),'013 one active credential each');
select phase10j_test.ok((select count(*)=1 from public.routine_operator_sessions where status='active'),'014 active operator session');
select phase10j_test.ok((select value->>'authenticated'='true' from phase10j_test.state where key='authenticated'),'015 authentication succeeded');
select phase10j_test.ok((select jsonb_array_length(value)=2 from phase10j_test.state where key='available'),'016 available list bounded');
select phase10j_test.ok((select value::text !~* 'pin|credential|email' from phase10j_test.state where key='available'),'017 list contains no credential detail');
select phase10j_test.ok((select value->'operator'->>'displayName'='Linked Test Operator' from phase10j_test.state where key='session'),'018 session operator snapshot');
select phase10j_test.ok((select value->'sharedDevice'->>'label'='Test Workbar' from phase10j_test.state where key='session'),'019 session device snapshot');
select phase10j_test.ok((select value->'capabilities'->>'taskActions'='true' from phase10j_test.state where key='session_context'),'020 effective task capability');
select phase10j_test.ok(not exists(select 1 from public.routine_operator_operations where response_payload::text~*'pin|secret|token'),'021 operation responses secret free');
select phase10j_test.ok(not exists(select 1 from public.routine_operator_events where payload::text~*'pin|secret|token'),'022 operator events secret free');
select phase10j_test.ok((select bool_and(pin_hash~E'^\\$2[abxy]\\$12\\$') from public.routine_operator_credentials),'023 bcrypt cost 12');
select phase10j_test.ok((select bool_and(hash_algorithm='bcrypt' and hash_cost=12) from public.routine_operator_credentials),'024 bcrypt metadata');
select phase10j_test.ok((select session_secret_hash=:'session_secret_hash' from public.routine_operator_sessions),'025 only supplied digest stored');
select phase10j_test.ok(not exists(select 1 from information_schema.columns where table_schema='public' and table_name like 'routine_operator_%' and column_name in('pin','session_token','session_secret')),'026 no raw secret columns');
select phase10j_test.ok(pg_get_functiondef('public.routine_parse_operator_session_token(text)'::regprocedure) like '%base64%','027 token decoded server side');
select phase10j_test.ok(pg_get_functiondef('public.routine_constant_time_equals(text,text)'::regprocedure) like '%#%','028 constant-time comparison helper');
select phase10j_test.ok(pg_get_functiondef('public.routine_operator_session_is_valid(uuid)'::regprocedure) like '%operator_revision_snapshot%','029 operator revision bound');
select phase10j_test.ok(pg_get_functiondef('public.routine_operator_session_is_valid(uuid)'::regprocedure) like '%access_revision_snapshot%','030 access revision bound');
select phase10j_test.ok(pg_get_functiondef('public.routine_operator_session_is_valid(uuid)'::regprocedure) like '%client.revoked_at is null%','031 revoked client invalidates');
select phase10j_test.ok(pg_get_functiondef('public.routine_resolve_effective_actor()'::regprocedure) like '%shared_device_operator%','032 shared effective actor');
select phase10j_test.ok(pg_get_functiondef('public.routine_resolve_actor()'::regprocedure) like '%routine_resolve_effective_actor%','033 legacy actor wrapper');
select phase10j_test.ok(pg_get_functiondef('public.routine_current_user_can_manage_templates()'::regprocedure) like '%personal_auth%','034 manager remains personal only');
select phase10j_test.ok(pg_get_functiondef('public.routine_current_user_can_coordinate_runs()'::regprocedure) like '%runCoordination%','035 coordination intersection');
select phase10j_test.ok(pg_get_functiondef('public.routine_current_user_can_perform_tasks()'::regprocedure) like '%taskActions%','036 task capability intersection');
select phase10j_test.ok(exists(select 1 from pg_indexes where indexname='routine_run_participants_operator_unique'),'037 run operator uniqueness');
select phase10j_test.ok(exists(select 1 from pg_indexes where indexname='routine_bundle_participants_operator_unique'),'038 bundle operator uniqueness');
select phase10j_test.ok(exists(select 1 from information_schema.columns where table_name='routine_run_participants' and column_name='identity_type'),'039 run participant identity type');
select phase10j_test.ok(exists(select 1 from information_schema.columns where table_name='routine_bundle_participants' and column_name='operator_id'),'040 bundle participant operator');
select phase10j_test.ok(pg_get_functiondef('public.join_routine_run(uuid,uuid)'::regprocedure) like '%shared_device_operator%','041 shared join implemented');
select phase10j_test.ok(pg_get_functiondef('public.routine_run_is_visible(uuid,uuid)'::regprocedure) like '%effective_operator_id%','042 run visibility operator scoped');
select phase10j_test.ok(pg_get_functiondef('public.routine_bundle_is_visible(uuid,uuid)'::regprocedure) like '%effective_operator_id%','043 bundle visibility operator scoped');
select phase10j_test.ok(exists(select 1 from information_schema.columns where table_name='routine_events' and column_name='authenticated_profile_id'),'044 authenticated profile audit');
select phase10j_test.ok(exists(select 1 from information_schema.columns where table_name='routine_events' and column_name='operator_session_id'),'045 event session audit');
select phase10j_test.ok(exists(select 1 from information_schema.columns where table_name='routine_runs' and column_name='finished_by_operator_id'),'046 run operator audit');
select phase10j_test.ok(exists(select 1 from information_schema.columns where table_name='routine_run_tasks' and column_name='completed_by_operator_id'),'047 task operator audit');
select phase10j_test.ok(exists(select 1 from information_schema.columns where table_name='routine_task_verifications' and column_name='verifier_operator_id'),'048 task verification operator audit');
select phase10j_test.ok(exists(select 1 from information_schema.columns where table_name='routine_run_verifications' and column_name='verifier_operator_id'),'049 run verification operator audit');
select phase10j_test.ok(pg_get_functiondef('public.routine_require_fresh_operator_credential(text,uuid)'::regprocedure) like '%operator_reauthentication_required%','050 reauth error stable');
select phase10j_test.ok(pg_get_functiondef('public.complete_routine_task(uuid,text,boolean,bigint,uuid)'::regprocedure) like '%complete_critical_task%','051 critical task reauth');
select phase10j_test.ok(pg_get_functiondef('public.finish_routine_run(uuid,bigint,uuid)'::regprocedure) like '%finish_routine_run%','052 finish reauth');
select phase10j_test.ok(pg_get_functiondef('public.complete_routine_event_transfer(uuid,text,jsonb,boolean,boolean,text,bigint,uuid)'::regprocedure) like '%complete_critical_event_transfer%','053 critical event reauth');
select phase10j_test.ok(pg_get_functiondef('public.routine_current_user_event_transfer_authority(text)'::regprocedure) like '%eventTransferActions%','054 event access intersection');
select phase10j_test.ok(pg_get_functiondef('public.routine_current_user_event_transfer_authority(text)'::regprocedure) like '%assigned_auth_user_id=v_profile.id%','055 linked event authority');
select phase10j_test.ok(exists(select 1 from pg_constraint where conname='routine_delivery_records_schema_check' and pg_get_constraintdef(oid) like '%phase10j-v3%'),'056 delivery v3 allowed');
select phase10j_test.ok(exists(select 1 from pg_constraint where conname='routine_delivery_items_schema_check' and pg_get_constraintdef(oid) like '%phase10j-v3%'),'057 item v3 allowed');
select phase10j_test.ok(pg_get_functiondef('public.routine_delivery_record_canonical_json(uuid)'::regprocedure) like '%operatorIdentity%','058 record hash identity');
select phase10j_test.ok(pg_get_functiondef('public.routine_delivery_item_canonical_json(uuid)'::regprocedure) like '%operatorIdentity%','059 item hash identity');
select phase10j_test.ok(pg_get_functiondef('public.preview_routine_run_delivery(uuid)'::regprocedure) like '%phase10j-v3%','060 shared preview v3');
select phase10j_test.ok(exists(select 1 from information_schema.columns where table_name='routine_client_instances' and column_name='shared_device_id'),'061 shared client binding');
select phase10j_test.ok((select shared_device_id is not null from public.routine_client_instances where id='1e200000-0000-4000-8000-000000000001'),'062 pre-session shared client registered');
select phase10j_test.ok(exists(select 1 from information_schema.columns where table_name='routine_offline_operation_receipts' and column_name='effective_operator_id'),'063 receipt operator identity');
select phase10j_test.ok(exists(select 1 from pg_indexes where indexname='routine_offline_receipts_operator_operation_unique'),'064 operator receipt replay key');
select phase10j_test.ok(pg_get_functiondef('public.apply_routine_offline_task_bundle(uuid,uuid,jsonb,text)'::regprocedure) like '%shared_device_critical_action_requires_online_reauthentication%','065 critical offline rejected');
select phase10j_test.ok(pg_get_functiondef('public.apply_routine_offline_run_finish_intent(uuid,uuid,uuid,bigint,timestamptz,text)'::regprocedure) like '%shared_device_run_finish_requires_online_reauthentication%','066 shared finish online only');
select phase10j_test.ok(pg_get_functiondef('public.get_routine_sync_events(timestamptz,uuid,integer,uuid[],uuid[])'::regprocedure) like '%cursor_polling%','067 shared cursor transport');
select phase10j_test.ok(pg_get_functiondef('public.get_routine_sync_events(timestamptz,uuid,integer,uuid[],uuid[])'::regprocedure) like '%effective_operator_id=v_actor.effective_operator_id%','068 null-run events operator scoped');
select phase10j_test.ok(pg_get_functiondef('public.get_routine_offline_operation_receipt(uuid,uuid)'::regprocedure) like '%effective_operator_id is not distinct%','069 receipt read operator scoped');
select phase10j_test.ok(to_regprocedure('public.get_routine_shared_device_context()') is not null,'070 device context RPC');
select phase10j_test.ok(to_regprocedure('public.get_routine_operator_session_context()') is not null,'071 session context RPC');
select phase10j_test.ok(to_regprocedure('public.get_routine_operator_security_history(date,date,uuid,uuid)') is not null,'072 security history RPC');
select phase10j_test.ok((select relrowsecurity from pg_class where oid='public.routine_operator_credentials'::regclass),'073 credential RLS enabled');
select phase10j_test.ok(not has_table_privilege('authenticated','public.routine_operator_credentials','select'),'074 credential table not selectable');
select phase10j_test.ok(not has_table_privilege('authenticated','public.routine_operator_sessions','select'),'075 session secret table not selectable');
select phase10j_test.ok(not has_table_privilege('authenticated','public.routine_operator_auth_attempts','insert'),'076 attempts direct insert denied');
select phase10j_test.ok(not exists(select 1 from pg_policies where schemaname='public' and tablename like 'routine_operator_%' and (qual~*'^true$' or with_check~*'^true$')),'077 no broad operator policy');
select phase10j_test.ok(not exists(select 1 from information_schema.role_table_grants where grantee='authenticated' and table_schema='public'
  and table_name in('routine_shared_devices','routine_operators','routine_shared_device_operator_access','routine_operator_credentials',
    'routine_operator_auth_throttles','routine_operator_auth_attempts','routine_operator_sessions','routine_operator_operations','routine_operator_events')
  and privilege_type in('INSERT','UPDATE','DELETE')),'078 no direct operator DML');
select phase10j_test.ok((select count(*)>=4 from public.routine_operator_events),'079 immutable security events written');
select phase10j_test.ok((select count(*)>=3 from public.routine_operator_operations),'080 immutable operation ledger written');
