-- Phase 10I server contract assertions. Each call raises immediately on a
-- failed invariant and emits one stable PASS line for the verifier.
create or replace function phase10i_test.ok(condition boolean,label text)
returns void language plpgsql as $$
begin
  if not coalesce(condition,false) then raise exception 'FAIL %',label; end if;
  raise notice 'PASS %',label;
end;
$$;

select phase10i_test.ok(to_regclass('public.routine_client_instances') is not null,'001 client instances table exists');
select phase10i_test.ok(to_regclass('public.routine_offline_operation_receipts') is not null,'002 receipts table exists');
select phase10i_test.ok(to_regclass('public.routine_delivery_reconciliations') is not null,'003 reconciliations table exists');
select phase10i_test.ok(not exists(select 1 from information_schema.columns where table_schema='public' and table_name in('routine_client_instances','routine_offline_operation_receipts','routine_delivery_reconciliations') and column_name='organization_id' and is_nullable='YES'),'004 organization ids are required');
select phase10i_test.ok(pg_get_functiondef('public.routine_client_instance_guard()'::regprocedure) like '%same-organization identity%','005 instance guard validates tenant identity');
select phase10i_test.ok(pg_get_functiondef('public.routine_offline_receipt_guard()'::regprocedure) like '%actor identity is invalid%','006 receipt guard validates actor identity');
select phase10i_test.ok(pg_get_functiondef('public.routine_delivery_reconciliation_guard()'::regprocedure) like '%same Opening task%','007 reconciliation guard validates task lineage');
select phase10i_test.ok(exists(select 1 from pg_constraint where conname='routine_offline_receipts_status_check'),'008 receipt status enum enforced');
select phase10i_test.ok(exists(select 1 from pg_constraint where conname='routine_delivery_reconciliations_trigger_check'),'009 reconciliation trigger enum enforced');
select phase10i_test.ok(exists(select 1 from pg_constraint where conname='routine_offline_receipts_hash_check'),'010 receipt SHA-256 shape enforced');
select phase10i_test.ok(exists(select 1 from pg_constraint where conname='routine_offline_receipts_client_time_check'),'011 client time can never be authoritative');
select phase10i_test.ok(exists(select 1 from pg_constraint where conname='routine_offline_receipts_operation_unique'),'012 client operation uniqueness enforced');
select phase10i_test.ok(exists(select 1 from pg_constraint where conname='routine_delivery_reconciliations_semantic_unique'),'013 reconciliation semantic uniqueness enforced');
select phase10i_test.ok(exists(select 1 from pg_constraint where conname='routine_client_instances_revision_check'),'014 positive instance revisions enforced');
select phase10i_test.ok(exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='routine_events'),'015 routine events published');
select phase10i_test.ok((select count(*)=1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='routine_events'),'016 event publication membership unique');
select phase10i_test.ok(not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and tablename like 'inventory_%'),'017 inventory not published by 10I');
select phase10i_test.ok(not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and tablename like 'asset_%'),'018 assets not published by 10I');
select phase10i_test.ok(not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and tablename like 'event_%'),'019 Event Operations not published by 10I');
select phase10i_test.ok(not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and tablename in('shift_sessions','task_completions','handover_notes')),'020 legacy not published by 10I');
select phase10i_test.ok(to_regclass('public.routine_events_org_cursor_idx') is not null,'021 organization cursor index exists');
select phase10i_test.ok(to_regclass('public.routine_events_org_run_cursor_idx') is not null,'022 run cursor index exists');
select phase10i_test.ok(to_regclass('public.routine_events_org_bundle_cursor_idx') is not null,'023 bundle cursor index exists');
select phase10i_test.ok((select count(*)>0 from public.routine_events),'024 event history retained');
select phase10i_test.ok((select count(*)=1 from public.routine_client_instances),'025 personal instance registered');
select phase10i_test.ok((select count(*)=1 from public.routine_events where event_type='client_instance_registered'),'026 registration event once');
select phase10i_test.ok((select auth_user_id=user_profile_id from public.routine_client_instances limit 1),'027 instance binds personal identity');
select phase10i_test.ok(pg_get_functiondef('public.touch_routine_client_instance(uuid,text,text)'::regprocedure) like '%owning actor%','028 touch is owner scoped');
select phase10i_test.ok(pg_get_functiondef('public.touch_routine_client_instance(uuid,text,text)'::regprocedure) like '%is revoked%','029 revoked touch rejected');
select phase10i_test.ok(pg_get_functiondef('public.revoke_routine_client_instance(uuid,bigint,text,uuid)'::regprocedure) like '%actor_auth_user_id%','030 self revoke supported');
select phase10i_test.ok(pg_get_functiondef('public.revoke_routine_client_instance(uuid,bigint,text,uuid)'::regprocedure) like '%actor_role<>''manager''%','031 manager revoke bounded');
select phase10i_test.ok(pg_get_functiondef('public.revoke_routine_client_instance(uuid,bigint,text,uuid)'::regprocedure) like '%organization_id<>v_actor.organization_id%','032 cross tenant revoke rejected');
select phase10i_test.ok(pg_get_functiondef('public.revoke_routine_client_instance(uuid,bigint,text,uuid)'::regprocedure) like '%40001%','033 stale revoke protected');
select phase10i_test.ok(pg_get_functiondef('public.register_routine_client_instance(uuid,text,text,text,uuid)'::regprocedure) like '%idempotentReplay%','034 registration replay explicit');
select phase10i_test.ok(pg_get_functiondef('public.routine_client_instance_guard()'::regprocedure) like '%cannot be deleted%','035 instance delete blocked');
select phase10i_test.ok(pg_get_functiondef('public.routine_phase10i_assert_instance(uuid,jsonb)'::regprocedure) like '%requires the actor own%','036 instance adds no authority');
select phase10i_test.ok(to_regprocedure('public.get_routine_sync_events(timestamptz,uuid,integer,uuid[],uuid[])') is not null,'037 cursor RPC exists');
select phase10i_test.ok(pg_get_functiondef('public.get_routine_sync_events(timestamptz,uuid,integer,uuid[],uuid[])'::regprocedure) like '%order by event.server_created_at,event.id%','038 cursor stable ordering');
select phase10i_test.ok(pg_get_functiondef('public.get_routine_sync_events(timestamptz,uuid,integer,uuid[],uuid[])'::regprocedure) like '%(event.server_created_at,event.id)>%','039 tuple cursor used');
select phase10i_test.ok(pg_get_functiondef('public.get_routine_sync_events(timestamptz,uuid,integer,uuid[],uuid[])'::regprocedure) like '%14 days%','040 null cursor lookback bounded');
select phase10i_test.ok(pg_get_functiondef('public.get_routine_sync_events(timestamptz,uuid,integer,uuid[],uuid[])'::regprocedure) like '%500%','041 cursor maximum enforced');
select phase10i_test.ok(pg_get_functiondef('public.get_routine_sync_events(timestamptz,uuid,integer,uuid[],uuid[])'::regprocedure) like '%input_run_ids is null%','042 run filter restrictive');
select phase10i_test.ok(pg_get_functiondef('public.get_routine_sync_events(timestamptz,uuid,integer,uuid[],uuid[])'::regprocedure) like '%input_bundle_ids is null%','043 bundle filter restrictive');
select phase10i_test.ok(pg_get_functiondef('public.get_routine_sync_events(timestamptz,uuid,integer,uuid[],uuid[])'::regprocedure) like '%routine_run_is_visible%','044 cursor rechecks visibility');
select phase10i_test.ok(pg_get_functiondef('public.get_routine_sync_events(timestamptz,uuid,integer,uuid[],uuid[])'::regprocedure) like '%actor_auth_user_id=v_actor.actor_auth_user_id%','045 actor instance events scoped');
select phase10i_test.ok(pg_get_functiondef('public.get_routine_sync_events(timestamptz,uuid,integer,uuid[],uuid[])'::regprocedure) like '%organization_id=v_actor.organization_id%','046 cursor exact organization');
select phase10i_test.ok(pg_get_functiondef('public.get_routine_sync_events(timestamptz,uuid,integer,uuid[],uuid[])'::regprocedure) like '%nextCursor%','047 next cursor returned');
select phase10i_test.ok(pg_get_functiondef('public.get_routine_sync_events(timestamptz,uuid,integer,uuid[],uuid[])'::regprocedure) like '%hasMore%','048 hasMore returned');
select phase10i_test.ok(pg_get_functiondef('public.get_routine_sync_events(timestamptz,uuid,integer,uuid[],uuid[])'::regprocedure) like '%affectedTaskIds%','049 affected IDs returned');
select phase10i_test.ok(pg_get_functiondef('public.routine_offline_receipt_guard()'::regprocedure) like '%immutable%','050 applied receipt immutable');
select phase10i_test.ok((select receipt_status='rejected' from public.routine_offline_operation_receipts limit 1),'051 rejected fixture receipt exists');
select phase10i_test.ok(pg_get_functiondef('public.routine_phase10i_existing_receipt(uuid,uuid,uuid,uuid,text)'::regprocedure) like '%idempotentReplay%','052 identical receipt replay');
select phase10i_test.ok(pg_get_functiondef('public.routine_phase10i_existing_receipt(uuid,uuid,uuid,uuid,text)'::regprocedure) like '%different request%','053 operation hash mismatch rejected');
select phase10i_test.ok(to_regprocedure('public.get_routine_offline_operation_receipt(uuid,uuid)') is not null,'054 receipt read RPC exists');
select phase10i_test.ok(exists(select 1 from pg_policies where schemaname='public' and tablename='routine_offline_operation_receipts' and policyname='routine_offline_receipts_select' and qual is not null),'055 receipt RLS actor scoped');
select phase10i_test.ok(pg_get_functiondef('public.get_routine_sync_health(date,date)'::regprocedure) not like '%response_payload%','056 sync health excludes payload');
select phase10i_test.ok(pg_get_functiondef('public.routine_offline_receipt_guard()'::regprocedure) like '%Sensitive keys%','057 receipt secrets rejected');
select phase10i_test.ok(pg_get_functiondef('public.get_routine_offline_operation_receipt(uuid,uuid)'::regprocedure) like '%return v_receipt%','058 unknown receipt returns null');
select phase10i_test.ok((public.routine_validate_offline_task_bundle(jsonb_build_object('taskId',(select id from public.routine_run_tasks limit 1),'baseTaskRevision',1,'clientRecordedAt',null,'initialAssessment',null,'itemUpdates','[]'::jsonb,'comments','[]'::jsonb,'finalAction','save_progress','pauseReason',null,'block',null,'notApplicableReason',null,'completionNote',null,'criticalConfirmation',false))->>'valid')::boolean,'059 valid bundle accepted');
select phase10i_test.ok(not(public.routine_validate_offline_task_bundle('{"extra":true}'::jsonb)->>'valid')::boolean,'060 unknown bundle key rejected');
select phase10i_test.ok(public.routine_validate_offline_task_bundle('{"baseTaskRevision":1,"itemUpdates":[],"comments":[],"finalAction":"save_progress"}'::jsonb)->>'errorCode'='offline_bundle_task_id_required','061 task ID required');
select phase10i_test.ok(public.routine_validate_offline_task_bundle(jsonb_build_object('taskId',gen_random_uuid(),'itemUpdates','[]'::jsonb,'comments','[]'::jsonb,'finalAction','save_progress'))->>'errorCode'='offline_bundle_base_revision_required','062 base revision required');
select phase10i_test.ok(pg_get_functiondef('public.routine_validate_offline_task_bundle(jsonb)'::regprocedure) like '%offline_bundle_duplicate_item%','063 duplicate items rejected');
select phase10i_test.ok(pg_get_functiondef('public.routine_validate_offline_task_bundle(jsonb)'::regprocedure) like '%>100%','064 item count bounded');
select phase10i_test.ok(pg_get_functiondef('public.routine_validate_offline_task_bundle(jsonb)'::regprocedure) like '%>20%','065 comment count bounded');
select phase10i_test.ok(pg_get_functiondef('public.routine_validate_offline_task_bundle(jsonb)'::regprocedure) like '%262144%','066 bundle bytes bounded');
select phase10i_test.ok(public.routine_validate_offline_task_bundle('{"block":{"password":"x"}}'::jsonb)->>'errorCode'='offline_bundle_forbidden_sensitive_key','067 recursive secret rejection');
select phase10i_test.ok(pg_get_functiondef('public.routine_validate_offline_task_bundle(jsonb)'::regprocedure) like '%offline_bundle_final_action_invalid%','068 final action closed');
select phase10i_test.ok(pg_get_functiondef('public.routine_validate_offline_task_bundle(jsonb)'::regprocedure) like '%offline_bundle_action_payload_inconsistent%','069 action fields consistent');
select phase10i_test.ok(pg_get_functiondef('public.routine_validate_offline_task_bundle(jsonb)'::regprocedure) like '%routine_validate_task_item_value%','070 typed item validator reused');
select phase10i_test.ok(pg_get_functiondef('public.routine_validate_offline_task_bundle(jsonb)'::regprocedure) not like '%input_payload->>''status''%','071 top-level status has no authority');
select phase10i_test.ok(to_regprocedure('public.apply_routine_offline_task_bundle(uuid,uuid,jsonb,text)') is not null,'072 bundle apply exists');
select phase10i_test.ok(pg_get_functiondef('public.apply_routine_offline_task_bundle(uuid,uuid,jsonb,text)'::regprocedure) like '%record_routine_initial_assessment%','073 assessment lifecycle reused');
select phase10i_test.ok(pg_get_functiondef('public.apply_routine_offline_task_bundle(uuid,uuid,jsonb,text)'::regprocedure) like '%update_routine_task_item%','074 item lifecycle reused');
select phase10i_test.ok(pg_get_functiondef('public.apply_routine_offline_task_bundle(uuid,uuid,jsonb,text)'::regprocedure) like '%add_routine_task_comment%','075 comments lifecycle reused');
select phase10i_test.ok(pg_get_functiondef('public.apply_routine_offline_task_bundle(uuid,uuid,jsonb,text)'::regprocedure) like '%complete_routine_task%','076 completion lifecycle reused');
select phase10i_test.ok(pg_get_functiondef('public.apply_routine_offline_task_bundle(uuid,uuid,jsonb,text)'::regprocedure) like '%exception when others%','077 subtransaction rollback boundary exists');
select phase10i_test.ok(pg_get_functiondef('public.apply_routine_offline_task_bundle(uuid,uuid,jsonb,text)'::regprocedure) like '%v_task.revision<>%baseTaskRevision%','078 task revision exact');
select phase10i_test.ok(pg_get_functiondef('public.apply_routine_offline_task_bundle(uuid,uuid,jsonb,text)'::regprocedure) like '%item.revision<>%baseRevision%','079 item revision exact');
select phase10i_test.ok(pg_get_functiondef('public.apply_routine_offline_task_bundle(uuid,uuid,jsonb,text)'::regprocedure) not like '%jsonb_set(input_payload%baseTaskRevision%','080 no automatic rebase');
select phase10i_test.ok(pg_get_functiondef('public.routine_phase10i_uuid(text)'::regprocedure) like '%md5%','081 substep keys deterministic');
select phase10i_test.ok(exists(select 1 from pg_constraint where conname='routine_offline_receipts_operation_unique'),'082 concurrent receipt last guard');
select phase10i_test.ok(pg_get_functiondef('public.routine_phase10i_conflict_payload(uuid,bigint,text)'::regprocedure) like '%currentRevision%','083 conflict exposes current state');
select phase10i_test.ok(pg_get_functiondef('public.routine_phase10i_conflict_payload(uuid,bigint,text)'::regprocedure) not like '%details%','084 conflict excludes evidence text');
select phase10i_test.ok(pg_get_functiondef('public.apply_routine_offline_task_bundle(uuid,uuid,jsonb,text)'::regprocedure) like '%server_rejected%','085 rejected path explicit');
select phase10i_test.ok(pg_get_functiondef('public.apply_routine_offline_task_bundle(uuid,uuid,jsonb,text)'::regprocedure) like '%not in(''40001'',''P0001'',''42501'') then raise%','086 unknown errors rethrown');
select phase10i_test.ok(pg_get_functiondef('public.apply_routine_offline_task_bundle(uuid,uuid,jsonb,text)'::regprocedure) like '%offline_timed_action_requires_online_confirmation%','087 timed completion conflict');
select phase10i_test.ok(pg_get_functiondef('public.apply_routine_offline_task_bundle(uuid,uuid,jsonb,text)'::regprocedure) like '%v_action in(''complete'',''not_applicable'')%','088 timed N/A conflict');
select phase10i_test.ok(strpos(pg_get_functiondef('public.apply_routine_offline_task_bundle(uuid,uuid,jsonb,text)'::regprocedure),'offline_timed_action_requires_online_confirmation')<strpos(pg_get_functiondef('public.apply_routine_offline_task_bundle(uuid,uuid,jsonb,text)'::regprocedure),'for update'),'089 timing conflict precedes mutation');
select phase10i_test.ok(pg_get_functiondef('public.apply_routine_offline_task_bundle(uuid,uuid,jsonb,text)'::regprocedure) like '%criticalConfirmation%','090 critical confirmation forwarded');
select phase10i_test.ok(pg_get_functiondef('public.apply_routine_offline_task_bundle(uuid,uuid,jsonb,text)'::regprocedure) like '%offline_evidence%','091 offline evidence created');
select phase10i_test.ok(exists(select 1 from pg_constraint where conname='routine_offline_receipts_client_time_check'),'092 client timestamp non-authority');
select phase10i_test.ok(pg_get_functiondef('public.apply_routine_offline_task_bundle(uuid,uuid,jsonb,text)'::regprocedure) like '%officialCompletedAt%','093 official completion time returned');
select phase10i_test.ok(pg_get_functiondef('public.apply_routine_offline_task_bundle(uuid,uuid,jsonb,text)'::regprocedure) not like '%set outcome%','094 evidence does not alter outcome');
select phase10i_test.ok(pg_get_functiondef('public.routine_validate_run_completion(uuid)'::regprocedure) like '%offline_action_time_unverified%','095 evidence completion warning');
select phase10i_test.ok(pg_get_functiondef('public.apply_routine_offline_task_bundle(uuid,uuid,jsonb,text)'::regprocedure) like '%offline-evidence:%','096 evidence ID operation scoped');
select phase10i_test.ok(pg_get_functiondef('public.apply_routine_offline_task_bundle(uuid,uuid,jsonb,text)'::regprocedure) like '%on conflict(id) do nothing%','097 evidence replay safe');
select phase10i_test.ok(to_regprocedure('public.apply_routine_offline_run_finish_intent(uuid,uuid,uuid,bigint,timestamptz,text)') is not null,'098 finish intent exists');
select phase10i_test.ok(pg_get_functiondef('public.apply_routine_offline_run_finish_intent(uuid,uuid,uuid,bigint,timestamptz,text)'::regprocedure) like '%v_run.revision<>input_base_run_revision%','099 finish revision exact');
select phase10i_test.ok(pg_get_functiondef('public.apply_routine_offline_run_finish_intent(uuid,uuid,uuid,bigint,timestamptz,text)'::regprocedure) like '%stale_revision%','100 stale finish conflict');
select phase10i_test.ok(pg_get_functiondef('public.apply_routine_offline_run_finish_intent(uuid,uuid,uuid,bigint,timestamptz,text)'::regprocedure) like '%exception when others%','101 finish failure rollback');
select phase10i_test.ok(pg_get_functiondef('public.apply_routine_offline_run_finish_intent(uuid,uuid,uuid,bigint,timestamptz,text)'::regprocedure) like '%finish_routine_run%','102 authoritative finish reused');
select phase10i_test.ok(pg_get_functiondef('public.finish_routine_run(uuid,bigint,uuid)'::regprocedure) like '%doubleShift%','103 Double Shift hook retained');
select phase10i_test.ok(pg_get_functiondef('public.apply_routine_offline_run_finish_intent(uuid,uuid,uuid,bigint,timestamptz,text)'::regprocedure) like '%existing_receipt%','104 finish replay receipt checked');
select phase10i_test.ok(pg_get_functiondef('public.routine_finalize_run_extension(uuid)'::regprocedure) like '%deliveryRecordId%','105 delivery finalization hooked');
select phase10i_test.ok(exists(select 1 from pg_constraint where conname='routine_offline_receipts_operation_unique'),'106 finish receipt stable');
select phase10i_test.ok(pg_get_functiondef('public.apply_routine_offline_run_finish_intent(uuid,uuid,uuid,bigint,timestamptz,text)'::regprocedure) like '%clientTimeAuthoritative'',false%','107 finish client time non-authority');
select phase10i_test.ok(to_regprocedure('public.routine_reconcile_opening_comparison_for_task(uuid,text,uuid,uuid,text)') is not null,'108 opening reconciliation helper exists');
select phase10i_test.ok(pg_get_functiondef('public.routine_finalize_run_extension(uuid)'::regprocedure) like '%routine_reconcile_delivery_comparisons_for_record%','109 late delivery auto reconciles');
select phase10i_test.ok(pg_get_functiondef('public.routine_reconcile_opening_comparison_for_task(uuid,text,uuid,uuid,text)'::regprocedure) like '%comparison_sequence,0)+1%','110 comparison sequence increments');
select phase10i_test.ok(pg_get_functiondef('public.routine_reconcile_opening_comparison_for_task(uuid,text,uuid,uuid,text)'::regprocedure) like '%v_latest.id%','111 latest comparison superseded');
select phase10i_test.ok(pg_get_functiondef('public.routine_delivery_immutable_guard()'::regprocedure) like '%immutable%','112 comparisons remain immutable');
select phase10i_test.ok(pg_get_functiondef('public.routine_reconcile_opening_comparison_for_task(uuid,text,uuid,uuid,text)'::regprocedure) like '%response_payload#>>''{deviation,id}''%','113 assessment deviation reused');
select phase10i_test.ok(pg_get_functiondef('public.routine_reconcile_opening_comparison_for_task(uuid,text,uuid,uuid,text)'::regprocedure) not like '%insert into public.routine_deviations%','114 reconciliation creates no deviation');
select phase10i_test.ok(pg_get_functiondef('public.routine_compare_opening_assessment_to_delivery(uuid,text,uuid,jsonb)'::regprocedure) like '%matched%','115 ready standard mapping retained');
select phase10i_test.ok(pg_get_functiondef('public.routine_compare_opening_assessment_to_delivery(uuid,text,uuid,jsonb)'::regprocedure) like '%mismatch%','116 issue standard mapping retained');
select phase10i_test.ok(pg_get_functiondef('public.routine_compare_opening_assessment_to_delivery(uuid,text,uuid,jsonb)'::regprocedure) like '%resolved_after_delivery%','117 ready override mapping retained');
select phase10i_test.ok(pg_get_functiondef('public.routine_compare_opening_assessment_to_delivery(uuid,text,uuid,jsonb)'::regprocedure) like '%confirmed_prior_deviation%','118 issue override mapping retained');
select phase10i_test.ok(pg_get_functiondef('public.routine_reconcile_opening_comparison_for_task(uuid,text,uuid,uuid,text)'::regprocedure) not like '%update public.routine_run_tasks%','119 assessment never rewritten');
select phase10i_test.ok(pg_get_functiondef('public.routine_reconcile_opening_comparison_for_task(uuid,text,uuid,uuid,text)'::regprocedure) not like '%update public.routine_delivery%','120 delivery never rewritten');
select phase10i_test.ok(pg_get_functiondef('public.routine_reconcile_opening_comparison_for_task(uuid,text,uuid,uuid,text)'::regprocedure) not like '%update public.routine_deviations%','121 resolved deviation not reopened');
select phase10i_test.ok(pg_get_functiondef('public.routine_reconcile_opening_comparison_for_task(uuid,text,uuid,uuid,text)'::regprocedure) like '%semantic_noop%','122 semantic no-op explicit');
select phase10i_test.ok(pg_get_functiondef('public.routine_reconcile_opening_comparison_for_task(uuid,text,uuid,uuid,text)'::regprocedure) like '%pg_advisory_xact_lock%','123 reconciliation concurrency lock');
select phase10i_test.ok(pg_get_functiondef('public.routine_delivery_reconciliation_guard()'::regprocedure) like '%immutable%','124 reconciliation immutable');
select phase10i_test.ok(exists(select 1 from pg_constraint where conname='routine_delivery_reconciliations_semantic_unique'),'125 reconciliation event semantic guard');
select phase10i_test.ok(pg_get_functiondef('public.routine_compute_delivery_reconciliation_hash(jsonb)'::regprocedure) like '%request_hash%','126 deterministic reconciliation hash');
select phase10i_test.ok(pg_get_functiondef('public.reopen_routine_run(uuid,text,bigint,uuid)'::regprocedure) like '%source_run_reopened%','127 reopen reconciliation hooked');
select phase10i_test.ok(pg_get_functiondef('public.routine_reconcile_delivery_comparisons_for_source_run(uuid,text)'::regprocedure) like '%reconcile_opening%','128 reopen recomputes openings');
select phase10i_test.ok(pg_get_functiondef('public.routine_select_previous_delivery_item_for_opening_task(uuid)'::regprocedure) like '%order by operational_date desc%','129 older fallback deterministic');
select phase10i_test.ok(pg_get_functiondef('public.routine_compare_opening_assessment_to_delivery(uuid,text,uuid,jsonb)'::regprocedure) like '%no_previous_delivery%','130 no previous fallback supported');
select phase10i_test.ok(pg_get_functiondef('public.routine_finalize_run_extension(uuid)'::regprocedure) like '%source_run_refinished%','131 refinish detected');
select phase10i_test.ok(pg_get_functiondef('public.routine_finalize_run_extension(uuid)'::regprocedure) like '%routine_reconcile_delivery_comparisons_for_record%','132 refinish reconciliation hooked');
select phase10i_test.ok(pg_get_functiondef('public.get_routine_delivery_reconciliation_history(uuid)'::regprocedure) like '%comparisonHistory%','133 full comparison history returned');
select phase10i_test.ok(pg_get_functiondef('public.routine_reconcile_opening_comparison_for_task(uuid,text,uuid,uuid,text)'::regprocedure) not like '%record_hash%:=%','134 delivery hashes immutable');
select phase10i_test.ok(pg_get_functiondef('public.routine_reconcile_opening_comparison_for_task(uuid,text,uuid,uuid,text)'::regprocedure) not like '%delete from public.routine_events%','135 source events retained');
select phase10i_test.ok((select qual like '%manager%' from pg_policies where tablename='routine_client_instances'),'136 manager sees own-org instances');
select phase10i_test.ok(exists(select 1 from pg_policies where tablename='routine_client_instances' and policyname='routine_client_instances_select' and qual is not null),'137 user sees own instances');
select phase10i_test.ok(exists(select 1 from pg_policies where tablename='routine_offline_operation_receipts' and policyname='routine_offline_receipts_select' and qual is not null),'138 user sees own receipts');
select phase10i_test.ok((select qual like '%routine_run_is_visible%' from pg_policies where tablename='routine_delivery_reconciliations'),'139 participant reconciliation visibility');
select phase10i_test.ok((select qual not like '% true%' from pg_policies where tablename='routine_delivery_reconciliations'),'140 no broad staff reconciliation');
select phase10i_test.ok(not exists(select 1 from pg_policies where tablename in('routine_client_instances','routine_offline_operation_receipts','routine_delivery_reconciliations') and (qual='true' or with_check='true')),'141 cross-org RLS bounded');
select phase10i_test.ok(pg_get_functiondef('public.routine_phase10i_assert_instance(uuid,jsonb)'::regprocedure) like '%organizationId%','142 cross-org RPC bounded');
select phase10i_test.ok((select qual not like '%counter%' from pg_policies where tablename='routine_client_instances'),'143 counter gets no access');
select phase10i_test.ok((select bool_and(qual like '%current_user_is_shared_device%') from pg_policies where tablename in('routine_client_instances','routine_offline_operation_receipts','routine_delivery_reconciliations')),'144 shared device blocked');
select phase10i_test.ok((select bool_and(qual like '%routine_current_user_is_active%') from pg_policies where tablename in('routine_client_instances','routine_offline_operation_receipts','routine_delivery_reconciliations')),'145 inactive user blocked');
select phase10i_test.ok((select bool_and(qual like '%organization_id = routine_current_user_organization_id%' or qual like '%organization_id = public.routine_current_user_organization_id%') from pg_policies where tablename in('routine_client_instances','routine_offline_operation_receipts','routine_delivery_reconciliations')),'146 org-less user blocked');
select phase10i_test.ok(not has_table_privilege('anon','public.routine_client_instances','SELECT'),'147 anon has no access');
select phase10i_test.ok(not has_table_privilege('authenticated','public.routine_offline_operation_receipts','INSERT') and not has_table_privilege('authenticated','public.routine_delivery_reconciliations','UPDATE'),'148 direct DML blocked');
