import React from "react";
import { createRoot } from "react-dom/client";
import "../../../styles.css";
import "../components/RoutineEngineShell.css";
import "../employee/RoutineEmployee.css";
import RoutineEmployeeHome from "../employee/RoutineEmployeeHome.jsx";
import RoutineRunWorkspace from "../employee/RoutineRunWorkspace.jsx";
import RoutineTaskDetails from "../employee/RoutineTaskDetails.jsx";
import RoutineTaskItemControl from "../employee/RoutineTaskItemControl.jsx";
import RoutineDeviationDialog from "../employee/RoutineDeviationDialog.jsx";
import RoutineNotApplicableDialog from "../employee/RoutineNotApplicableDialog.jsx";
import RoutineCompletionDialog from "../employee/RoutineCompletionDialog.jsx";
import RoutineCriticalReauthDialog from "../employee/RoutineCriticalReauthDialog.jsx";
import RoutineReferenceInline from "../employee/RoutineReferenceInline.jsx";
import RoutineReferenceViewer from "../employee/RoutineReferenceViewer.jsx";
import RoutineHandoverPanel from "../employee/RoutineHandoverPanel.jsx";
import RoutineTransferPanel from "../employee/RoutineTransferPanel.jsx";
import RoutineRunFinishPanel from "../employee/RoutineRunFinishPanel.jsx";
import RoutineVerificationPanel from "../employee/RoutineVerificationPanel.jsx";
import RoutineDoubleShiftWorkspace from "../employee/RoutineDoubleShiftWorkspace.jsx";
import RoutineDoubleShiftChangeFeed from "../employee/RoutineDoubleShiftChangeFeed.jsx";
import RoutineOfflineState from "../employee/RoutineOfflineState.jsx";
import RoutineConflictPanel from "../employee/RoutineConflictPanel.jsx";

export const EMPLOYEE_VISUAL_SCENARIOS = Object.freeze([
  "employee-home-staff","employee-home-manager","employee-home-shared","shadow-read-only","empty-content","opening-run","closing-run","do-now-grouping","in-progress-other","waiting-blocked",
  "upcoming-next","overdue-deadline","completed-corrections","assessment-ready","assessment-correction","assessment-control-issue","item-check","item-count-quantity","item-choice-status","item-source-identity",
  "comment-network-preserved","deviation-dialog","not-applicable-dialog","critical-completion","shared-pin-reauth","task-stale-conflict","offline-queued","timed-offline-blocked","reference-placeholder","reference-image",
  "reference-fullscreen","previous-closing-matched","previous-closing-mismatch","prior-override-deviation","handover-draft","handover-submit-accept","transfer-proposed","event-recipient-evidence","run-finish-blockers","closing-responsible-verification",
  "delivery-preview","run-finished","ds01","ds02","between-shifts","change-feed-updated","ds03","closing-reassignment","ds04","mobile-320",
  "mobile-390","mobile-430","dark-mode","zoom-200","keyboard-task-flow","shared-session-expiry","realtime-disconnected","cursor-polling-shared","legacy-back","staff-no-preview"
]);

const scenario = new URLSearchParams(location.search).get("scenario") || EMPLOYEE_VISUAL_SCENARIOS[0];
const id = (suffix) => `73000000-0000-4000-8000-${suffix.padStart(12, "0")}`;
const allowed = { allowed: true, reasonCode: null }; const denied = { allowed: false, reasonCode: "routine_server_policy_denied" };
const noop = () => {}; const successApi = new Proxy({}, { get: () => async () => ({ ok: true, data: {} }) });
const taskBase = { id: id("1"), run_id: id("100"), title_snapshot: "Inspect the north entrance and complete the physical security handover", location_name_snapshot: "North entrance · street-level door", done_when_snapshot: "Door, latch and alarm contact are physically checked.", status: "in_progress", revision: 7, sort_order_snapshot: 1, criticality_snapshot: "important", outcome: null, timing: { live: { phase: "due", reasonCode: "due", nextBoundaryAt: "2026-08-06T10:30:00Z", secondsLate: 0 } }, actorRelationship: { isAssigned: true, assignedTo: { displayName: "Mina Larsen", role: "staff" } }, actions: { canClaim: denied, canRelease: denied, canStart: denied, canPause: allowed, canAssess: denied, canUpdateItems: allowed, canComment: allowed, canBlock: allowed, canMarkNotApplicable: allowed, canComplete: allowed, canReopen: denied, canVerify: denied, canTransfer: allowed }, activeDeviations: [] };
const taskContext = { task: taskBase, timing: taskBase.timing, dependencyStatus: { valid: true, blockers: [], dependencies: [] }, actorRelationship: taskBase.actorRelationship,
  initialAssessmentPolicy: { policy: "ready_on_arrival", recorded: false, allowedChoices: ["ready", "correction_required"] }, items: [], notApplicablePolicy: "allowed_with_reason", criticality: "important", verificationPolicy: "second_person_required", activeDeviations: [], activeOverride: null,
  previousDelivery: { operationalDate: "2026-08-05", reportedStatus: "standard_met", completedBy: "Alex N.", verifier: "Closing Responsible", operationalAgeDays: 1, evidence: ["Door secured at 03:42"] }, comparison: { result: "matched", label: "Matched previous Closing" }, referenceImages: [], actions: taskBase.actions, criticalReauthRequired: false, offlinePolicy: { completionQueueAllowed: true, timedNotApplicableOnlineOnly: false } };
const tasks = [
  { ...taskBase, id: id("1"), status: "not_started", title_snapshot: "Set the entrance to opening standard", timing: { live: { phase: "available", reasonCode: "available" } } },
  { ...taskBase, id: id("2"), title_snapshot: "Inspect the full bar perimeter and exceptionally long service boundary", actorRelationship: { isAssigned: false, assignedTo: { displayName: "Oskar Berg", role: "staff" } } },
  { ...taskBase, id: id("3"), status: "blocked", title_snapshot: "Restore glasswash temperature", waiting_reason: "dependency", timing: { live: { phase: "pending_condition", reasonCode: "routine_task_condition_pending" } }, activeDeviations: [{ id: id("31"), severity: "critical", category: "equipment", status: "open" }] },
  { ...taskBase, id: id("4"), status: "not_started", title_snapshot: "Prepare reservation signage", timing: { live: { phase: "upcoming", reasonCode: "routine_task_too_early", nextBoundaryAt: "2026-08-06T11:00:00Z" } } },
  { ...taskBase, id: id("5"), status: "not_started", title_snapshot: "Confirm emergency exits", timing: { live: { phase: "hard_deadline_passed", reasonCode: "hard_deadline_passed", secondsLate: 780 } } },
  { ...taskBase, id: id("6"), status: "completed", title_snapshot: "Count clean service trays", outcome: "completed_after_correction", completed_by_display_name_snapshot: "Mina Larsen", completed_at: "2026-08-06T09:58:00Z", timing: { live: { phase: "handled", reasonCode: "routine_task_handled" } } }
];
const runContext = { run: { id: id("100"), routineKey: "Opening", routine_key: "Opening", scopeKey: "Main bar", scope_key: "Main bar", operationalDate: "2026-08-06", operational_date: "2026-08-06", status: "in_progress", revision: 12, templateVersionNumber: 3, template_version_number_snapshot: 3, snapshotState: "ready", timing_snapshot_state: "ready", tasks, runVerifications: [], activeRoleAssignments: [{ roleKey: "opening_responsible", displayName: "Mina Larsen" }] }, participant: { id: id("200"), displayName: "Mina Larsen", role: "staff", revision: 2 }, actorRole: "staff",
  actions: { canJoin: denied, canStartRun: denied, canRequestFinalVerification: denied, canVerifyRun: denied, canFinish: denied, canReopen: denied, canCancel: denied }, progress: { total: 6, handled: 1, remaining: 5, criticalRemaining: 1, blocked: 1, deviationCount: 1 }, currentVerifications: [], completionValidation: { valid: false, blockers: ["mandatory_tasks_incomplete", "important_deviations_unresolved"], warnings: ["hard_deadline_passed"], requiredVerificationTasks: [{ taskId: id("6"), revision: 7 }] }, deliveryPreview: { hasDeliveryContract: true, proposedItems: [{ label: "Entrance condition", reportedStatus: "standard_met" }] }, handoverRequirements: [], pendingTransfers: [], activeResponsibilities: [], criticalReauthRequired: false, offlinePolicy: { serverReceiptRequired: true }, readOnlyPreview: false };
const home = { contractVersion: "phase10k3-v1", uiReleaseStage: "staff_preview", mode: "shadow", readOnlyPreview: false, operationalAllowed: true, identity: { displayName: "Mina Larsen", actorSource: "personal_auth", role: "staff" }, operationalClock: { operationalDate: "2026-08-06", serverNow: "2026-08-06T10:08:00Z", timezone: "Europe/Oslo" }, sync: { transport: "postgres_realtime", status: "online", serverConfirmed: true }, currentRuns: [{ id: id("100"), routineKey: "Opening", scopeKey: "Main bar", status: "in_progress", operationalDate: "2026-08-06", templateVersionNumber: 3 }], joinableRuns: [{ id: id("101"), routineKey: "Closing", status: "scheduled", operationalDate: "2026-08-06", canJoin: true }], startableTemplates: [{ templateId: id("301"), name: "Opening", routineKey: "opening", action: allowed }], doubleShiftBundles: [{ id: id("400"), status: "between_shifts", operationalDate: "2026-08-06" }], assignedTasks: [{ id: id("2"), runId: id("100"), title: "Inspect the bar perimeter", location: "Main bar", status: "in_progress" }], openDeviations: [{ id: id("31"), category: "equipment", severity: "critical", status: "open" }], pendingHandovers: [{ id: id("500"), handoverType: "shift_transition", status: "submitted" }], pendingTransfers: [{ id: id("600"), targetType: "participant", status: "proposed", reason: "Closing ownership" }], eventTransferRequests: [], emptyStateReason: null };
const handoverContext = { handover: { id: id("500"), status: "draft", summary: "Glasswash temperature remains under observation.", revision: 3 }, actorRelation: "source", items: [{ id: id("501"), source: "generated", title: "Critical glasswash deviation" }, { id: id("502"), source: "manual", title: "Check terrace heater before return" }], actions: { canEdit: allowed, canRefresh: allowed, canSubmit: allowed, canAccept: denied } };
const transferContext = { transfer: { id: id("600"), status: "accepted", reason: "Event team completes the room reset", revision: 4 }, actorRelation: "event_target", sourceTask: { title: "Reset private room", location: "Library room" }, eventContext: { evidenceRequirements: { items: [{ id: id("601"), itemType: "check", label: "Room physically checked", required: true }] } }, actions: { canAccept: denied, canReject: denied, canComplete: allowed, canCancel: denied }, criticalConfirmationRequired: true };
const dsContext = { bundle: { bundle: { id: id("400"), status: "between_shifts", operationalDate: "2026-08-06", operational_date: "2026-08-06", expected_closing_start_at: "2026-08-06T18:00:00Z", revision: 8 }, currentParticipant: { id: id("401"), revision: 3 }, runs: { opening: { id: id("100"), status: "finished" }, closing: { id: id("101"), status: "scheduled" } }, eventContext: { label: "Private room reception · 18:30" }, missingCriticalRoles: [] }, expectedReturnAt: "2026-08-06T17:00:00Z", actualReturnAt: null, changeFeed: { hash: "7d54b7…98c1", entries: [{ id: "feed-1", type: "Event timing", summary: "Private room timing moved 30 minutes", serverCreatedAt: "10:14" }] }, reassignmentState: { closingAssignedTo: "Mina Larsen" }, openingSummary: { status: "finished", corrections: 1, openDeviations: 1, rooms: "Ready", technicalIssues: 1 }, closingSummary: { status: "scheduled" }, pendingEventTransfers: [], ds04Summary: { personalOutcome: "Opening contribution recorded", openingContribution: "Complete", closingContribution: "Pending" }, actions: { canConfirmDS01: allowed, canSubmitDS02: allowed, canReturnDS03: allowed, canReassignClosing: denied }, readOnlyPreview: false };

function Frame({ children, title = "Operational Employee Workflow" }) { return <div className="routine-shell"><main className="employee-workspace"><header className="employee-page-header"><button type="button">← Preview Home</button><div><p className="eyebrow">Visual harness · {scenario}</p><h1>{title}</h1></div></header>{children}</main></div>; }
function HomeHarness() { let value = home; if (scenario === "employee-home-manager") value = { ...home, identity: { ...home.identity, displayName: "Robert Manager", role: "manager" } }; if (scenario === "employee-home-shared" || scenario === "cursor-polling-shared") value = { ...home, identity: { displayName: "Nora Operator", actorSource: "shared_device_operator", role: "staff", device: { displayName: "Workbar North" } }, sync: { transport: "cursor_polling", status: "online", serverConfirmed: true } }; if (scenario === "shadow-read-only") value = { ...home, readOnlyPreview: true, operationalAllowed: false, readOnlyMessage: "Read-only preview — operational actions are not enabled", joinableRuns: [], startableTemplates: home.startableTemplates.map((entry) => ({ ...entry, action: denied })) }; if (scenario === "empty-content") value = { ...home, currentRuns: [], joinableRuns: [], startableTemplates: [], doubleShiftBundles: [], assignedTasks: [], openDeviations: [], pendingHandovers: [], pendingTransfers: [], emptyStateReason: "routine_no_published_content" }; return <div className="routine-shell"><RoutineEmployeeHome home={value} onBack={noop} onOpenRun={noop} onOpenBundle={noop} runApi={successApi} doubleShiftApi={successApi} /></div>; }
function TaskHarness({ mutate = {} }) { const context = { ...taskContext, ...mutate, task: { ...taskContext.task, ...(mutate.task ?? {}) }, actions: { ...taskContext.actions, ...(mutate.actions ?? {}) } }; const actionApi = scenario === "comment-network-preserved" ? new Proxy({}, { get: () => async () => ({ ok: false, mode: "network_error", message: "Network unavailable" }) }) : successApi; return <Frame title={context.task.title_snapshot}><RoutineTaskDetails context={context} onConfirmed={noop} actionApi={actionApi} reauthApi={async () => ({ ok: true })} online={scenario !== "timed-offline-blocked"} /></Frame>; }
function ItemHarness() { const sets = scenario === "item-check" ? [{ itemType: "check", label: "Alarm contact responds", required: true }] : scenario === "item-count-quantity" ? [{ itemType: "count", label: "Clean service trays", required: true }, { itemType: "measurement", label: "Glasswash temperature", unit: "°C", required: true }] : scenario === "item-choice-status" ? [{ itemType: "choice", label: "Door state", options: ["Secure", "Needs attention"], required: true }, { itemType: "status", label: "Inspection result", options: ["Pass", "Fail"], required: true }] : [{ itemType: "location", label: "Terrace bar", sourceIdentity: { name: "Terrace bar · LOC-03" }, required: true }, { itemType: "asset", label: "Glasswasher", sourceIdentity: { name: "Glasswasher · ASSET-12" } }, { itemType: "product", label: "Coffee beans", sourceIdentity: { name: "House espresso · PROD-08" } }]; return <Frame title="Typed task items"><section className="employee-items">{sets.map((item, index) => <RoutineTaskItemControl key={index} item={item} value={item.itemType === "check" ? false : ""} onChange={noop} onSave={noop} />)}</section></Frame>; }
function DialogHarness() { if (scenario === "deviation-dialog") return <Frame><RoutineDeviationDialog onClose={noop} onSubmit={noop} /></Frame>; if (scenario === "not-applicable-dialog") return <Frame><RoutineNotApplicableDialog task={taskBase} policy="allowed_with_reason" online onClose={noop} onSubmit={noop} /></Frame>; if (scenario === "shared-pin-reauth") return <Frame><RoutineCriticalReauthDialog onClose={noop} onAuthenticated={noop} api={async () => ({ ok: false, data: {} })} /></Frame>; return <Frame><RoutineCompletionDialog context={{ ...taskContext, task: { ...taskBase, criticality_snapshot: "critical" }, criticality: "critical", activeDeviations: [{ severity: "critical", category: "security" }] }} onClose={noop} onSubmit={noop} /></Frame>; }
function ReferenceHarness() { const reference = { id: id("700"), state: scenario === "reference-placeholder" ? "placeholder" : "active_image", caption: "Approved north entrance latch", altText: "Brass latch fully seated in the north entrance frame", objectPath: "server/returned/pinned/path" }; if (scenario === "reference-fullscreen") return <Frame><RoutineReferenceViewer reference={reference} source="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='900' height='600'%3E%3Crect width='900' height='600' fill='%23182f3d'/%3E%3Crect x='330' y='80' width='240' height='440' rx='32' fill='%23d8a957'/%3E%3Ccircle cx='500' cy='300' r='58' fill='%23131d25'/%3E%3C/svg%3E" onClose={noop} /></Frame>; return <Frame><RoutineReferenceInline reference={reference} downloader={async () => ({ ok: true, blob: new Blob(["<svg xmlns='http://www.w3.org/2000/svg' width='900' height='600'><rect width='900' height='600' fill='#18303d'/><circle cx='450' cy='300' r='120' fill='#d8a957'/></svg>"], { type: "image/svg+xml" }) })} /></Frame>; }
function AuxiliaryHarness() { if (scenario.startsWith("handover")) { const value = scenario === "handover-submit-accept" ? { ...handoverContext, handover: { ...handoverContext.handover, status: "submitted" }, actorRelation: "target", actions: { canEdit: denied, canRefresh: denied, canSubmit: denied, canAccept: allowed } } : handoverContext; return <Frame><RoutineHandoverPanel handoverId={value.handover.id} initialContext={value} loader={async () => value} api={successApi} /></Frame>; } if (["transfer-proposed","event-recipient-evidence"].includes(scenario)) { const value = scenario === "transfer-proposed" ? { ...transferContext, transfer: { ...transferContext.transfer, status: "proposed" }, eventContext: null, actorRelation: "target", actions: { canAccept: allowed, canReject: allowed, canComplete: denied, canCancel: denied } } : transferContext; return <Frame><RoutineTransferPanel transferId={value.transfer.id} initialContext={value} loader={async () => value} api={successApi} /></Frame>; } if (scenario === "closing-responsible-verification") return <Frame><RoutineVerificationPanel title="Closing Responsible verification" revision={12} policy="closing_responsible" executor="Mina Larsen" canVerify={allowed} requiredTasks={[{ title: "North entrance", revision: 7 }]} onVerify={noop} /></Frame>; return <Frame><RoutineRunFinishPanel context={scenario === "run-finished" ? { ...runContext, run: { ...runContext.run, status: "finished" }, completionValidation: { valid: true, blockers: [], warnings: [] } } : runContext} onAction={noop} /></Frame>; }
function OfflineHarness() { if (scenario === "task-stale-conflict") return <Frame><RoutineConflictPanel conflict={{ serverRevision: 8, serverSummary: { status: "in_progress", actor: "Oskar" }, localRevision: 7, localSummary: { completionNote: "Door checked", itemDraft: "Secure" }, actor: "Oskar", at: "2026-08-06T10:11:00Z" }} onRefresh={noop} onKeep={noop} onDiscard={noop} onCreateNew={noop} /></Frame>; const state = scenario === "shared-session-expiry" ? { transport: "cursor_polling", status: "auth_required" } : scenario === "realtime-disconnected" ? { transport: "postgres_realtime", status: "disconnected" } : { transport: "offline_bundle", status: "queued" }; const overlayState = scenario === "timed-offline-blocked" ? "rejected" : scenario === "shared-session-expiry" ? "operator_auth_required" : scenario === "realtime-disconnected" ? "sync_pending" : "queued"; const overlay = [{ operationId: "op-1", label: scenario === "timed-offline-blocked" ? "Timed completion rejected — online required" : "Complete entrance inspection", state: overlayState, serverConfirmed: false }]; return <Frame><RoutineOfflineState sync={state} overlay={overlay} /></Frame>; }
function DoubleShiftHarness() { let value = dsContext; if (scenario === "change-feed-updated") return <Frame title="Double Shift change feed"><RoutineDoubleShiftChangeFeed feed={value.changeFeed} stale onRefresh={noop} /></Frame>; if (scenario === "ds01") value = { ...value, bundle: { ...value.bundle, bundle: { ...value.bundle.bundle, status: "planned" } } }; if (scenario === "ds02") value = { ...value, bundle: { ...value.bundle, bundle: { ...value.bundle.bundle, status: "opening_finished" } } }; if (scenario === "ds03") value = { ...value, bundle: { ...value.bundle, bundle: { ...value.bundle.bundle, status: "return_due" } } }; if (scenario === "closing-reassignment") value = { ...value, reassignmentState: { closingAssignedTo: "Oskar Berg", originalOpeningContributor: "Mina Larsen" }, actions: { ...value.actions, canReassignClosing: allowed } }; if (scenario === "ds04") value = { ...value, bundle: { ...value.bundle, bundle: { ...value.bundle.bundle, status: "completed" } }, ds04Summary: { personalOutcome: "Double Shift completed", openingContribution: "Mina Larsen", closingContribution: "Oskar Berg", reassignments: 1, delivery: "Generated" } }; return <div className="routine-shell"><RoutineDoubleShiftWorkspace bundleId={id("400")} onBack={noop} onOpenRun={noop} loader={async () => value} api={successApi} /></div>; }
function RunHarness() { let value = runContext; if (scenario === "closing-run") value = { ...value, run: { ...value.run, routineKey: "Closing", routine_key: "Closing" } }; return <div className="routine-shell"><RoutineRunWorkspace runId={value.run.id} onBack={noop} loader={async () => value} taskLoader={async () => taskContext} runApi={successApi} taskApi={successApi} reauthApi={async () => ({ ok: true })} subscribe={() => noop} /></div>; }
function AccessHarness() { return <Frame title={scenario === "legacy-back" ? "Legacy navigation preserved" : "Operations Preview unavailable"}><section className="employee-empty"><div><h2>{scenario === "legacy-back" ? "Return to current shift log" : "Preview access required"}</h2><p>{scenario === "legacy-back" ? "Opening and Closing legacy navigation remains unchanged." : "This staff profile has no Routine Engine preview membership."}</p><button type="button">{scenario === "legacy-back" ? "Back to shift log" : "Preview Home"}</button></div></section></Frame>; }
function Harness() {
  if (["employee-home-staff","employee-home-manager","employee-home-shared","shadow-read-only","empty-content","cursor-polling-shared","mobile-320","mobile-390","mobile-430","dark-mode","zoom-200"].includes(scenario)) return <HomeHarness />;
  if (["opening-run","closing-run","do-now-grouping","in-progress-other","waiting-blocked","upcoming-next","overdue-deadline","completed-corrections","keyboard-task-flow"].includes(scenario)) return <RunHarness />;
  if (["assessment-ready","assessment-correction","assessment-control-issue","comment-network-preserved","previous-closing-matched","previous-closing-mismatch","prior-override-deviation"].includes(scenario)) return <TaskHarness mutate={scenario === "comment-network-preserved" ? { actions: { canComment: allowed } } : scenario === "previous-closing-mismatch" ? { comparison: { result: "mismatch", label: "Mismatch — server deviation opened" } } : scenario === "prior-override-deviation" ? { activeOverride: { reason: "Temporary manager acceptance", remainingRisk: "Low" }, activeDeviations: [{ severity: "important", category: "delivery" }] } : scenario === "assessment-control-issue" ? { initialAssessmentPolicy: { policy: "control_result", recorded: false }, actions: { canAssess: allowed } } : scenario.startsWith("assessment-") ? { actions: { canAssess: allowed } } : {}} />;
  if (["item-check","item-count-quantity","item-choice-status","item-source-identity"].includes(scenario)) return <ItemHarness />;
  if (["deviation-dialog","not-applicable-dialog","critical-completion","shared-pin-reauth"].includes(scenario)) return <DialogHarness />;
  if (["task-stale-conflict","offline-queued","timed-offline-blocked","shared-session-expiry","realtime-disconnected"].includes(scenario)) return <OfflineHarness />;
  if (["reference-placeholder","reference-image","reference-fullscreen"].includes(scenario)) return <ReferenceHarness />;
  if (["handover-draft","handover-submit-accept","transfer-proposed","event-recipient-evidence","run-finish-blockers","closing-responsible-verification","delivery-preview","run-finished"].includes(scenario)) return <AuxiliaryHarness />;
  if (["ds01","ds02","between-shifts","change-feed-updated","ds03","closing-reassignment","ds04"].includes(scenario)) return <DoubleShiftHarness />;
  return <AccessHarness />;
}

const rootElement = document.getElementById("root");
const employeeHarnessRoot = rootElement.__routineEmployeeRoot ?? createRoot(rootElement);
rootElement.__routineEmployeeRoot = employeeHarnessRoot;
employeeHarnessRoot.render(<Harness />);
